FLUSH PRIVILEGES;

CREATE DATABASE wordpress;

CREATE USER 'root'@'0.0.0.0' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'0.0.0.0';

CREATE USER 'root'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';

FLUSH PRIVILEGES;
